name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL
      run: sudo apt-get install libsdl2-dev
    - name: Install vcpkg
      run: cargo install cargo-vcpkg
    - name: Build vcpkg
      run: cargo vcpkg build
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
